language: clojure
lein: 2.9.8
dist: focal
jdk:
script: lein do cljfmt check, eastwood, test :all
  -openjdk11
deploy:
  provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
